-- spec/fixtures/groundtruth/monterey.lua
-- Known-good Monterey-Bay marine ground truth from iNaturalist research-grade
-- observations (scientific/genus/family via GBIF). Generated by
-- scripts/build-inat-corpus.lua. Images are gitignored (spec/fixtures/images/).
return {
	{ image = "inat_216648.jpg", common = "Pacific Viperfish", scientific = "Chauliodus macouni", genus = "Chauliodus", family = "Stomiidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_232769.jpg", common = "King-of-the-salmon", scientific = "Trachipterus altivelis", genus = "Trachipterus", family = "Trachipteridae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_130235.jpg", common = "Greater Moon Jelly", scientific = "Aurelia labiata", genus = "Aurelia", family = "Ulmaridae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_117731.jpg", common = "cockscomb nudibranch", scientific = "Antiopella barbarensis", genus = "Antiopella", family = "Janolidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_1426070.jpg", common = "Tuna Crab", scientific = "Grimothea planipes", genus = "Grimothea", family = "Munididae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_56083.jpg", common = "Common Pill Woodlouse", scientific = "Armadillidium vulgare", genus = "Armadillidium", family = "Armadillidiidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_554753.jpg", common = "Hoodwinker Mola", scientific = "Mola tecta", genus = "Mola", family = "Molidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_49848.jpg", common = "California Aglaja", scientific = "Navanax inermis", genus = "Navanax", family = "Aglajidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_121181.jpg", common = "Jeweled Top Snail", scientific = "Calliostoma annulatum", genus = "Calliostoma", family = "Calliostomatidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_337277.jpg", common = "Giant Bell Jelly", scientific = "Scrippsia pacifica", genus = "Scrippsia", family = "Corynidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_49053.jpg", common = "Gumboot Chiton", scientific = "Cryptochiton stelleri", genus = "Cryptochiton", family = "Acanthochitonidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_82128.jpg", common = "Basking Shark", scientific = "Cetorhinus maximus", genus = "Cetorhinus", family = "Cetorhinidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_334556.jpg", common = "Derby Hat Bryozoan", scientific = "Integripelta bilabiata", genus = "Integripelta", family = "Eurystomellidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_48479.jpg", common = "Pacific Sea Nettle", scientific = "Chrysaora fuscescens", genus = "Chrysaora", family = "Pelagiidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_479764.jpg", common = "Sand Rose Anemone", scientific = "Urticina columbiana", genus = "Urticina", family = "Actiniidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_69839.jpg", common = "Purple-striped Sea Nettle", scientific = "Chrysaora colorata", genus = "Chrysaora", family = "Pelagiidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_49723.jpg", common = "Northern Kelp Crab", scientific = "Pugettia producta", genus = "Pugettia", family = "Epialtidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_60636.jpg", common = "Nudibranch-mimicking Amphipod", scientific = "Podocerus cristatus", genus = "Podocerus", family = "Podoceridae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_1149649.jpg", common = "Sea Cherub", scientific = "Cliopsis krohnii", genus = "Cliopsis", family = "Cliopsidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
	{ image = "inat_48975.jpg", common = "Pear Marginella", scientific = "Granulina margaritula", genus = "Granulina", family = "Granulinidae", lat = 36.62, lng = -121.9, source = "inaturalist:monterey" },
}
