-- spec/fixtures/groundtruth/reference.lua
-- Ground-truth species labels for the offline REFERENCE corpus — a hand-picked
-- set of well-known species across several phyla, with the accepted scientific
-- name / genus / family resolved against the GBIF backbone. Generated by
-- scripts/build-corpus.lua. Nothing here is tied to any person or account; the
-- image slugs are descriptive (the offline suite replays recorded JSON, not pixels).
return {
	{ image = "spotfin_porcupinefish.jpg", common = "Spot-fin porcupinefish", scientific = "Diodon hystrix", genus = "Diodon", family = "Diodontidae", order = "Tetraodontiformes", class = "", phylum = "Chordata", kingdom = "Animalia", source = "reference" },
	{ image = "spotted_linckia.jpg", common = "Multipore sea star", scientific = "Linckia multifora", genus = "Linckia", family = "Ophidiasteridae", order = "Valvatida", class = "Asteroidea", phylum = "Echinodermata", kingdom = "Animalia", source = "reference" },
	{ image = "reef_octopus_triggerfish.jpg", common = "Day octopus", scientific = "Octopus cyanea", genus = "Octopus", family = "Octopodidae", order = "Octopoda", class = "Cephalopoda", phylum = "Mollusca", kingdom = "Animalia", source = "reference" },
	{ image = "reef_octopus_triggerfish.jpg", common = "Lei triggerfish", scientific = "Sufflamen bursa", genus = "Sufflamen", family = "Balistidae", order = "Tetraodontiformes", class = "", phylum = "Chordata", kingdom = "Animalia", source = "reference" },
	{ image = "snowflake_moray.jpg", common = "Snowflake moray", scientific = "Echidna nebulosa", genus = "Echidna", family = "Muraenidae", order = "Anguilliformes", class = "", phylum = "Chordata", kingdom = "Animalia", source = "reference" },
	{ image = "african_buffalo.jpg", common = "African buffalo", scientific = "Syncerus caffer", genus = "Syncerus", family = "Bovidae", order = "Artiodactyla", class = "Mammalia", phylum = "Chordata", kingdom = "Animalia", source = "reference" },
	{ image = "california_golden_gorgonian.jpg", common = "California golden gorgonian", scientific = "Muricea californica", genus = "Muricea", family = "Plexauridae", order = "Malacalcyonacea", class = "Anthozoa", phylum = "Cnidaria", kingdom = "Animalia", source = "reference" },
	{ image = "ocean_sunfish.jpg", common = "Ocean sunfish", scientific = "Mola mola", genus = "Mola", family = "Molidae", order = "Tetraodontiformes", class = "", phylum = "Chordata", kingdom = "Animalia", source = "reference" },
	{ image = "hooded_nudibranch.jpg", common = "Hooded nudibranch", scientific = "Melibe leonina", genus = "Melibe", family = "Tethydidae", order = "Nudibranchia", class = "Gastropoda", phylum = "Mollusca", kingdom = "Animalia", source = "reference" },
	{ image = "bornean_orangutan.jpg", common = "Bornean orangutan", scientific = "Pongo pygmaeus", genus = "Pongo", family = "Hominidae", order = "Primates", class = "Mammalia", phylum = "Chordata", kingdom = "Animalia", source = "reference" },
	{ image = "wolf_eel.jpg", common = "Wolf-eel", scientific = "Anarrhichthys ocellatus", genus = "Anarrhichthys", family = "Anarhichadidae", order = "Perciformes", class = "", phylum = "Chordata", kingdom = "Animalia", source = "reference" },
	{ image = "bald_eagle.jpg", common = "Bald eagle", scientific = "Haliaeetus leucocephalus", genus = "Haliaeetus", family = "Accipitridae", order = "Accipitriformes", class = "Aves", phylum = "Chordata", kingdom = "Animalia", source = "reference" },
}
