require 'support.fixtures'
local Config = require 'Config'

describe( 'Config.load', function()
	it( 'returns defaults when prefs is nil', function()
		local c = Config.load( nil )
		assert.equal( 'lens', c.backend )
		assert.equal( 'flat', c.keywordMode )
		assert.is_false( c.lensKeepOpen )
		assert.is_false( c.firstRunDone )
		assert.is_true( c.autoApplyThreshold > 0 )
	end )
	it( 'overlays stored prefs on the defaults', function()
		local c = Config.load { autoApplyThreshold = 0.8, keywordMode = 'both' }
		assert.equal( 'lens', c.backend )      -- untouched default
		assert.equal( 0.8, c.autoApplyThreshold )
		assert.equal( 'both', c.keywordMode )
	end )
	it( 'has dropped the retired Vision / Pl@ntNet / SerpApi / image-host settings', function()
		local c = Config.load( nil )
		assert.is_nil( c.visionApiKey )
		assert.is_nil( c.plantNetKey )
		assert.is_nil( c.plantNetProject )
		assert.is_nil( c.serpApiKey )
		assert.is_nil( c.useImageHost )
	end )
end )

describe( 'Config.validate', function()
	it( 'accepts the Google Lens backend with no credential (self-generated session)', function()
		assert.is_true( ( Config.validate( Config.load { backend = 'lens' } ) ) )
	end )
	it( 'rejects an unknown backend', function()
		local ok, why = Config.validate( Config.load { backend = 'nope' } )
		assert.is_false( ok )
		assert.matches( 'Unknown backend', why )
	end )
end )
