require 'support.fixtures'
local Config = require 'Config'

describe( 'Config.load', function()
	it( 'returns defaults when prefs is nil', function()
		local c = Config.load( nil )
		assert.equal( 'lens', c.backend )
		assert.equal( 'both', c.keywordMode )
		assert.equal( 'all', c.plantNetProject )
		assert.is_true( c.autoApplyThreshold > 0 )
	end )
	it( 'overlays stored prefs on the defaults', function()
		local c = Config.load { backend = 'vision', autoApplyThreshold = 0.8 }
		assert.equal( 'vision', c.backend )
		assert.equal( 0.8, c.autoApplyThreshold )
		assert.equal( 'both', c.keywordMode ) -- untouched default
	end )
	it( 'has dropped the SerpApi / image-host settings', function()
		local c = Config.load( nil )
		assert.is_nil( c.serpApiKey )
		assert.is_nil( c.useImageHost )
		assert.is_nil( c.imageHost )
	end )
end )

describe( 'Config.validate', function()
	it( 'accepts the Google Lens backend with no credential (self-generated session)', function()
		assert.is_true( ( Config.validate( Config.load { backend = 'lens' } ) ) )
		assert.is_true( ( Config.validate( Config.load { backend = 'lens', lensCookie = 'NID=abc' } ) ) )
	end )
	it( 'requires a key for the Vision backend', function()
		assert.is_false( ( Config.validate( Config.load { backend = 'vision' } ) ) )
		assert.is_true( ( Config.validate( Config.load { backend = 'vision', visionApiKey = 'k' } ) ) )
	end )
	it( 'requires a key for the Pl@ntNet backend', function()
		assert.is_false( ( Config.validate( Config.load { backend = 'plantnet' } ) ) )
		assert.is_true( ( Config.validate( Config.load { backend = 'plantnet', plantNetKey = 'k' } ) ) )
	end )
	it( 'rejects an unknown backend', function()
		assert.is_false( ( Config.validate( Config.load { backend = 'nope' } ) ) )
	end )
end )
