#!/usr/bin/env lua
--[[----------------------------------------------------------------------------
scripts/build-inat-corpus.lua
Build a known-good Monterey-Bay marine ground-truth set from iNaturalist
research-grade observations (community-verified; the practical stand-in for the
SIMoN database, which is scrape-hostile). For each distinct species it downloads
a photo into spec/fixtures/images/ (gitignored) and records the accepted
scientific name / genus / family (resolved through GBIF, like the pipeline) plus
the observation's location, into spec/fixtures/groundtruth/monterey.lua.

That set is used by `scripts/live-accuracy.lua --groundtruth fixtures.groundtruth.monterey`
to measure + tune real Lens accuracy on location-relevant marine species.

NOTE on accuracy reads: these are web photos, so Lens may find the exact iNat page
(inflating its score) — good for tuning the parser/scorer across many taxa, less so
as a real-world read on novel photos. Run from any network (iNat + GBIF are open).
Usage:  lua scripts/build-inat-corpus.lua [--n 24]
------------------------------------------------------------------------------]]

package.path = table.concat( { 'src/shared/?.lua', 'build/.deps/?.lua', package.path }, ';' )
local json = require 'dkjson'
local Taxonomy = require 'Taxonomy'

local N = 24
for i, a in ipairs( arg ) do if a == '--n' then N = tonumber( arg[ i + 1 ] ) or N end end

-- Monterey Bay NMS centre; everything we pull is location-relevant to here.
local LAT, LNG, RADIUS = 36.62, -121.90, 40
local IMAGES = 'spec/fixtures/images'
local UA = 'lightroom-species-tagger/0.1 (ground-truth builder)'

local function shquote( s ) return "'" .. tostring( s ):gsub( "'", "'\\''" ) .. "'" end
local function run( cmd ) local h = io.popen( cmd ); local o = h:read( '*a' ); h:close(); return o end
local function curlJson( url )
	local body = run( 'curl -fsS -A ' .. shquote( UA ) .. ' ' .. shquote( url ) .. ' 2>/dev/null' )
	return body and body ~= '' and json.decode( body ) or nil
end

local resolveHttp = { get = function( url ) return run( 'curl -fsS ' .. shquote( url ) .. ' 2>/dev/null' ) end }

print( ('Fetching iNaturalist research-grade marine observations near Monterey (target %d species)…'):format( N ) )
os.execute( 'mkdir -p ' .. IMAGES )

local seen, dataset = {}, {}
local page = 1
while #dataset < N and page <= 6 do
	local url = ( 'https://api.inaturalist.org/v1/observations?lat=%s&lng=%s&radius=%s&quality_grade=research' ..
		'&photos=true&rank=species&iconic_taxa=Mollusca,Actinopterygii,Animalia&order_by=votes&per_page=30&page=%d' )
		:format( LAT, LNG, RADIUS, page )
	local d = curlJson( url )
	if not d or not d.results then break end
	for _, o in ipairs( d.results ) do
		if #dataset >= N then break end
		local t = o.taxon or {}
		local sci = t.name
		local common = t.preferred_common_name
		local photos = o.photos or {}
		local purl = photos[ 1 ] and photos[ 1 ].url
		if sci and common and purl and t.rank == 'species' and not seen[ sci ] then
			-- GBIF match for accepted scientific + genus/family (pipeline's source of truth)
			local tx = Taxonomy.matchScientific( sci, { http = resolveHttp, cache = {} } )
			if tx and tx.genus and tx.family then
				seen[ sci ] = true
				local imgUrl = purl:gsub( 'square', 'medium' )
				local fname = ( 'inat_%d.jpg' ):format( t.id or #dataset )
				run( 'curl -fsS -A ' .. shquote( UA ) .. ' -o ' .. shquote( IMAGES .. '/' .. fname ) ..
					' ' .. shquote( imgUrl ) .. ' 2>/dev/null' )
				dataset[ #dataset + 1 ] = {
					image = fname, common = common, scientific = tx.scientificName,
					genus = tx.genus, family = tx.family, lat = LAT, lng = LNG,
				}
				print( ( '  %-28s -> %-26s %s / %s' ):format( common, tx.scientificName, tx.genus, tx.family ) )
			end
		end
	end
	page = page + 1
end

local function q( s ) return ( '%q' ):format( s or '' ) end
local out = {
	'-- spec/fixtures/groundtruth/monterey.lua',
	'-- Known-good Monterey-Bay marine ground truth from iNaturalist research-grade',
	'-- observations (scientific/genus/family via GBIF). Generated by',
	'-- scripts/build-inat-corpus.lua. Images are gitignored (spec/fixtures/images/).',
	'return {',
}
for _, r in ipairs( dataset ) do
	out[ #out + 1 ] = ( '\t{ image = %s, common = %s, scientific = %s, genus = %s, family = %s, lat = %s, lng = %s, source = "inaturalist:monterey" },' )
		:format( q( r.image ), q( r.common ), q( r.scientific ), q( r.genus ), q( r.family ), tostring( r.lat ), tostring( r.lng ) )
end
out[ #out + 1 ] = '}'
os.execute( 'mkdir -p spec/fixtures/groundtruth' )
local f = assert( io.open( 'spec/fixtures/groundtruth/monterey.lua', 'wb' ) )
f:write( table.concat( out, '\n' ) .. '\n' ); f:close()
print( ( '\nWrote spec/fixtures/groundtruth/monterey.lua (%d species) + images in %s/' ):format( #dataset, IMAGES ) )
